# Identité du projet sur le serveur SonarQube
sonar.projectKey=TommyK78---TaskList-Backend
sonar.projectName=TommyK78 - TaskList Backend

# URL du serveur SonarQube de l'école
sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr

# Code source à analyser (et ce qu'on exclut de l'analyse)
sonar.sources=src
sonar.exclusions=src/__tests__/**,**/*.test.ts

# Déclaration des tests
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts

# Rapport de couverture généré par Vitest (format lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
